num_workers: 4
pin_memory: True
non_blocking: True
prefetch: False
amp: False
device: cuda
client_optimizer: sgd
client_optimizer_parameters:
    momentum: 0.9
    weight_decay: 0.0005
dataset: cifar10
dataset_path: ./data
frequency_save: 0
batch_size: 128
lr: 0.01
lr_scheduler: CosineAnnealingLR
model: preactresnet18
random_seed: 0
epochs: 100
