attack_label_trans: all2one
attack_target: 0
pratio: 0.1
attack: badnet
patch_mask_path: ./resource/badnet/trigger_image.png
cover_rate: 0.5
mask_rate: 0.1
center_loss_weight: 1.0
center_loss_momentum: 0.99
