checkpoint_save:
log:
device: 'cuda'
amp: True
pin_memory: True
non_blocking: True
prefetch: False

dataset_path: './data'
dataset: 'cifar10'

batch_size: 256
num_workers: 4

random_seed: 0

num_starts: 40
optimize_steps: 300

lr: 0.01
client_optimizer: sgd
client_optimizer_parameters:
    momentum: 0.2
lr_scheduler:
